require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'run_examples.rb'

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Lint
Lint/MissingSuper:
  Exclude:
    - 'lib/offers/**/*'

# Style
Style/Documentation:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'run_examples.rb'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

# RSpec
RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ContextWording:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

# Disable problematic Capybara predicate matcher cop (known RuboCop bug)
Capybara/RSpec/PredicateMatcher:
  Enabled: false

